config/routes.rb
Rails.application.routes.draw do
  root 'members#index'
  resources :pairs
  resources :members

  get 'roulette/pair/table' => 'pairs#roulette', as: :roulette
  get 'roulette/history/:members' => 'pairs#history', as: :history
  get 'roulette' => 'roulettes#new', as: :new_roulette
  post 'roulette/result/' => 'roulettes#result', as: :result_roulette
  get 'roulette/swap' => 'roulettes#swap', as: :roulette_swap

end

app/models/coba.rb
class Coba < ActiveRecord::Base
  attr_accessor :member1, :member2, :details
end

app/models/member.rb
class Member < ActiveRecord::Base
  scope :by_name, -> {order('name ASC')}

  validates :name, presence: true
end

app/models/pair.rb
class Pair < ActiveRecord::Base
  attr_accessor :member1, :member2

  validates :members, presence: true
  validates :status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coba_controller.rb
class CobaController < ApplicationController

  def index

  end
  def roulette
    @member = Member.all
    @total  = @member.count
    #random member before use
    rand(@total).times do
      @member = @member.shuffle
    end
    @t_pair = (@total/ 2) + (@total % 2)
    @result = []
    @t_pair.times do
      if @total >= 2
        @result << ["Pair", @member[0] , @member[1]]
        @member = @member.drop(2)
        @total = @total-2
      else
        @result << ["Solo", @member[0] , @member[0]]
        @member = @member.drop(1)
        @total = @total-1
      end
    end
    @pairs = []
    @t_pair.times do
      @pairs << Pair.new
    end
    @counter = 0
  end

  def result
    @pairs = params[:pair]
    Pair.update_all status: "done"
    @pairs.each do |index, pair|
      new_pair = Pair.new
      new_pair.members = pair[:member1], pair[:member2]
      new_pair.details = pair[:details]
      new_pair.status = "active"
      new_pair.save
    end
    redirect_to roulette_path
  end

  private
  def set_coba
  end

  def coba_params
    params.require(:pair).permit(:member1, :member2, :details, :status)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name)
    end
end

app/controllers/pairs_controller.rb
class PairsController < ApplicationController
  before_action :set_pair, only: [:show, :edit, :update, :destroy]

  # GET /pairs
  # GET /pairs.json
  def index
    @pairs = Pair.all
  end

  # GET /pairs/1
  # GET /pairs/1.json
  def show
  end

  # GET /pairs/new
  def new
    @pair = Pair.new
  end

  # GET /pairs/1/edit
  def edit
  end

  # POST /pairs
  # POST /pairs.json
  def create
    @pair = Pair.new(pair_params)
    puts pair_params
    @pair.members = pair_params[:member1], pair_params[:member2]
    respond_to do |format|
      if @pair.save
        format.html { redirect_to @pair, notice: 'Pair was successfully created.' }
        format.json { render :show, status: :created, location: @pair }
      else
        format.html { render :new }
        format.json { render json: @pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pairs/1
  # PATCH/PUT /pairs/1.json
  def update
    @pair.members = pair_params[:member1], pair_params[:member2]
    respond_to do |format|
      if @pair.update(pair_params)
        format.html { redirect_to @pair, notice: 'Pair was successfully updated.' }
        format.json { render :show, status: :ok, location: @pair }
      else
        format.html { render :edit }
        format.json { render json: @pair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pairs/1
  # DELETE /pairs/1.json
  def destroy
    @pair.destroy
    respond_to do |format|
      format.html { redirect_to pairs_url, notice: 'Pair was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def roulette
    @member1 = Member.all.by_name
    @member2 = Member.all.by_name
    @pairs = Pair.all

    #position
    @x = 0
    @y = 0
  end

  def history
    members = "#{params[:members]}".delete("{").delete("}")
    members = members.split(",")
    @pairs = Pair.where("members=? OR members =?", "#{params[:members]}", "{#{members[1]},#{members[0]}}")
    @nama1 = Member.find(members[0]).name
    @nama2 = Member.find(members[1]).name
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pair
      @pair = Pair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pair_params
      params.require(:pair).permit(:members, :details, :member1, :member2)
    end
end

app/controllers/roulettes_controller.rb
class RoulettesController < ApplicationController
  def index

  end
  def new
    @member = Member.all
    @total  = @member.count
    #random member before use
    rand(@total).times do
      @member = @member.shuffle
    end
    @t_pair = (@total/ 2) + (@total % 2)
    @result = []
    @t_pair.times do
      if @total >= 2
        @result << ["Pair", @member[0] , @member[1]]
        @member = @member.drop(2)
        @total = @total-2
      else
        @result << ["Solo", @member[0] , @member[0]]
        @member = @member.drop(1)
        @total = @total-1
      end
    end
    @pairs = []
    @t_pair.times do
      @pairs << Pair.new
    end
    @counter = 0
  end

  def result
    @pairs = params[:pair]
    puts params[:pair]
    Pair.update_all status: "done"
    @pairs.each do |index, pair|
      new_pair = Pair.new
      new_pair.members = pair[:member1], pair[:member2]
      new_pair.details = pair[:details]
      new_pair.status = "active"
      new_pair.save
    end
    # redirect_to roulette_path
  end

  def swap
    @pairs = Pair.where(status: "active")
    @counter = 0
    @formasi = []
    i = 0
    @pairs.each do |p|
      @formasi << ["pair_[#{i}][member1]",  p.members[0].to_i]
      @formasi << ["pair_[#{i}][member2]",  p.members[1].to_i]
      i = i+1
    end
    @formasi =  @formasi.to_json
  end

  private
  def set_coba
  end

  def coba_params
    params.require(:pair).permit(:member1, :member2, :details, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/pairs_helper.rb
module PairsHelper
end

app/helpers/roulettes_helper.rb
module RoulettesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Roulette" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Roulette</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "1", "/#"  %></li>
            <li><%= link_to "2", "/#"  %></li>
            <li><%= link_to "3", "/#"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Pair", pairs_path  %></li>
              <li><%= link_to "Pair Table", roulette_path  %></li>
              <li><%= link_to "Members", members_path  %></li>
              <li><%= link_to "Swap", roulette_swap_path   %></li>
              <li><%= link_to "Roulette", new_roulette_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; KMKAkademy 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/members/_form.html.erb
<%= form_for @member, :html => { :class => "form-horizontal member" } do |f| %>

  <% if @member.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                members_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/members/edit.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/index.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.id, member_path(member) %></td>
        <td><%= member.name %></td>
        <td><%=l member.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_member_path(member), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      member_path(member),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_member_path,
            :class => 'btn btn-primary' %>

app/views/members/new.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/members/show.html.erb
<%- model_class = Member -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @member.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              members_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_member_path(@member), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              member_path(@member),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/pairs/_form.html.erb
<%= form_for @pair, :html => { :class => "form-horizontal pair" } do |f| %>

  <% if @pair.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@pair.errors.count, "error") %> prohibited this pair from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @pair.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :members, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select(:member1, Member.all, :id, :name) %>
    </div>
    <div class="col-lg-10">
      <%= f.collection_select(:member2, Member.all, :id, :name) %>
    </div>
    <%=f.error_span(:members) %>
  </div>
  <div class="form-group">
    <%= f.label :details, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :details, :class => 'form-control' %>
    </div>
  </div>
    <%=f.error_span(:details) %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                pairs_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/pairs/edit.html.erb
<%- model_class = Pair -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pairs/history.html.erb
<%- model_class = Pair -%>
<div class="page-header">
  <h1>Pairs History</h1>
  <% if(@nama1 == @nama2)%>
    <h3>Solo : <%= @nama1 %></h3>
  <% else %>
    <h3><%= @nama1+" and "+@nama2 %></h3>
    <%end%>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <% @pairs.each do |pair| %>
      <tr>
        <td><%=l pair.created_at.localtime.to_datetime %></td>
        <td><%= pair.details %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pairs/index.html.erb
<%- model_class = Pair -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:members) %></th>
      <th><%= model_class.human_attribute_name(:details) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pairs.each do |pair| %>
      <tr>
        <td><%= link_to pair.id, pair_path(pair) %></td>
        <td><%= pair.members %></td>
        <td><%= pair.details %></td>
        <td><%= pair.status %></td>
        <td><%=l pair.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_pair_path(pair), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      pair_path(pair),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pair_path,
            :class => 'btn btn-primary' %>

app/views/pairs/new.html.erb
<%- model_class = Pair -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pairs/roulette.html.erb
<%- model_class = Pair -%>
<div class="page-header">
  <h1>Pair Table</h1>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Pair</th>
      <% @member1.each do |m| %>
        <th class="warning"><%= m.name %></th>
    <% end %>
    </tr>
  </thead>
  <tbody>
  <% @member1.each do |m1|%>
    <%@y=0 %>
  <tr>
    <td class="success" >
      <%= m1.name%>
    </td>
    <% @member2.each do |m2|%>
      
      <% if @x > @y %>
        <td class="info" title="Pair">
        <%= link_to history_path(:members => "{#{m2.id}, #{m1.id}}") do %>
        <%= @pairs.where(members: "{#{m1.id}, #{m2.id}}").count + @pairs.where(members: "{#{m2.id}, #{m1.id}}").count%>
      <%end%>
    </td>
      <%elsif @x == @y %>
        <td class="danger" title="Solo">
        <%= link_to history_path(:members => "{#{m2.id}, #{m1.id}}") do %>
          <%=@pairs.where(members: "{#{m1.id}, #{m2.id}}").count %>
        <%end%>
      </td>
    <%else%>
      <td class="active"></td>
      <%end%>
      
      <% @y = @y+1%>
  <% end %>
</tr>
<%@x = @x+1%>
<% end %>
  </tbody>
</table>

<p>
<table class="table">
  <tr>
    <td class="info" title="coba"></td>
    <td >Pair</td>
  </tr>
  <tr>
    <td class="danger"></td>
    <td>Solo</td>
  </tr>
</table>

</p>

app/views/pairs/show.html.erb
<%- model_class = Pair -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:members) %>:</strong></dt>
  <dd><%= @pair.members %></dd>
  <dt><strong><%= model_class.human_attribute_name(:details) %>:</strong></dt>
  <dd><%= @pair.details %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              pairs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_pair_path(@pair), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              pair_path(@pair),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/roulettes/index.html.erb
<div>
  <h1>Create Swap Member</h1>
</div>

app/views/roulettes/new.html.erb
<div>
  <h1>Random Roulette</h1>
</div>
<div class="panel panel-info">
  <%= form_tag result_roulette_path %>
    <table class="table table-striped table-bordered table-hover">
      <tr>
        <th>?</th>
        <th colspan="2">Team</th>
        <th> Description </th>
      </tr>
      <% @result.each do |status, m1, m2|%>
        <%= hidden_field_tag "pair[#{@counter}][member1]", m1.id %>
        <%= hidden_field_tag "pair[#{@counter}][member2]", m2.id %>
          <% if status == "Pair"%>
            <tr class="success">
            <td ><%= status%></td>
          <td ><%= m1.name%></td>
          <td ><%= m2.name%></td>
          <td ><%= text_field_tag "pair[#{@counter}][details]" %> </td>
        </tr>
      <%else%>
        <tr class="danger">
        <%= hidden_field_tag "pair[#{@counter}][member1]", m1.id %>
        <%= hidden_field_tag "pair[#{@counter}][member2]", m1.id %>
          <td ><%= status%></td>
          <td colspan="2"><%= m1.name%></td>
          <td ><%= text_field_tag "pair[#{@counter}][details]" %> </td>
        </tr>
      <%end%>
      <%@counter = @counter+1%>
      <%end%>

    </table>
    <%= submit_tag %>
  </form>
    <%= link_to "Roulette Again !", new_roulette_path %>
  </div>

app/views/roulettes/result.html.erb
coba

app/views/roulettes/swap.html.erb
<div>
  <h1>Swap Pairs</h1>
</div>
<div class="panel panel-info">
  <%= form_tag result_roulette_path %>
  <table class="table table-striped table-bordered table-hover">
    <tr>
      <th>?</th>
      <th colspan="2">Team</th>
      <th> Description </th>
    </tr>
    <% @pairs.each do |p|%>
      <tr class="success">
      <td >
        <%= collection_select(:pair, "[#{@counter}][member1]", Member.all,:id,:name, {selected: p.members[0]}, { onchange: "change_member(#{p.members[0]}, 'pair_[#{@counter}][member1]')" }) %>
      </td>
      <td>
        <%= collection_select(:pair, "[#{@counter}][member2]", Member.all,:id,:name, {selected: p.members[1]}, { onchange: "change_member(#{p.members[1]}, 'pair_[#{@counter}][member2]')" }) %>
      </td>
      <td ><%= p.status%></td>
      <td ><%= text_field_tag "pair[#{@counter}][details]", p.details %> </td>
    </tr>
    <%@counter = @counter+1%>
  <%end%>
  </table>
  <%= submit_tag %>
</form>
  </div>

  <div id="data-member" data-member="<%=@formasi%>">
  </div>